name: Code Quality (PR to ino_dev)

on:
  pull_request:
    branches: [ "ino_dev" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout kodu
        uses: actions/checkout@v4

      - name: Instalacja cppcheck
        run: sudo apt-get update && sudo apt-get install -y cppcheck

      - name: Analiza statyczna (cppcheck)
        run: cppcheck --enable=warning,style --error-exitcode=0 .
